### ISSUE TITLE
Typographical and grammatical errors

### ISSUE THREAD

**Issue by agh208** [health-data-science-OR/coding-for-ml#39]
https://www.pythonhealthdatascience.com/content/01_algorithms/02_oop/01_python_classes.html
Original sentence: "A text hosptial adventure" (title)
Suggested fix: "A text hospital adventure"

https://www.pythonhealthdatascience.com/content/02_stat_prog/01_pandas/01_intro_pandas.html
Original sentence: ### pd.DataFrame
Suggested fix: Run the cell so displays as a title rather than code
Original sentence: We can also select a multiple columns.
Suggested fix: We can also select multiple columns.

https://www.pythonhealthdatascience.com/content/02_stat_prog/01_pandas/02_files.html
Original sentence: Given the naming convention in the dataset we can the .filter for columns containing the string smoothness and call the decribe method.
Suggested fix: Change "the" to "use" and change "decribe" to "describe": Given the naming convention in the dataset we can use .filter for columns containing the string smoothness and call the describe method.

**Comment by agh208** [comment]
https://www.pythonhealthdatascience.com/content/02_stat_prog/01_pandas/03_non_standard_download.html
Original: How do download a remote data source
Fix: How to download a remote data source.

**Comment by TomMonks** [comment]
thanks @agh208 

these are all fixed in dev and will be merged into v2.0.0 of the book for the new academic year.
