### ISSUE TITLE
Spelling/Grammar/Images

### ISSUE THREAD

**Issue by agh208** [health-data-science-OR/coding-for-ml#42]
https://www.pythonhealthdatascience.com/content/03_mgt/02_packaging/01_python_packages.html
Original: "I think for the most part its best try creating one for yourself"
Suggested fix: "I think for the most part it's best to try creating one for yourself"

https://www.pythonhealthdatascience.com/content/03_mgt/04_exercises/01_python_packages.html
When downloaded as an .ipynb file, the figures for exercise 6 are not visible - just a little photo symbol and then the name of the picture.

**Comment by TomMonks** [comment]
Thanks Amy will get these fixed when I am done marking!

**Comment by TomMonks** [comment]
thanks @agh208 

I've fixed the first typo.  this in in dev v2.0.0

I couldn't recreate the second. When I opened this in Jupyter the figures were there.  I've updated the course to use the latest version of Jupyter Lab - possibly this fixes the issue.  But I'll keep an eye on it.  Thanks!
