### ISSUE TITLE
Issue on page /content/001_setup/conda.html

### ISSUE THREAD

**Issue by reevesglobal** [health-data-science-OR/coding-for-ml#52]
Hey Thomas :)
The second sentence on this page reads a bit awkwardly: "To create the conda environment issues the following command on a terminal" 
I suggest changing it to something like: "To create the conda environment, enter the following commands into the terminal"

**Comment by TomMonks** [comment]
Thank you. I have rephrased the sentence. I will add your name to the contributors file.  Your help is v.much appreciated!

**Comment by TomMonks** [comment]
deployed in release 2.0.1
