### ISSUE TITLE
Issue on page /content/001_setup/conda.html 

### ISSUE THREAD

**Issue by trptaylor** [health-data-science-OR/coding-for-ml#53]
Hi Thomas,

Beginner user here so please ignore if I have missed something obvious but I thought it might be worth mentioning that in your page on creating the Conda virtual environment, the fourth line of code wouldn't run:

conda create -f binder/environment.yml

I think this is because it is should be conda env create -f binder/environment.yml

**Comment by TomMonks** [comment]
deployed in release 2.0.1
