### ISSUE TITLE
Issue on page /contenhttps://www.pythonhealthdatascience.com/content/01_algorithms/04_exercises/02_array.html

### ISSUE THREAD

**Issue by ploginovic** [health-data-science-OR/coding-for-ml#58]
Minor typo in Exercise 8 description. The description says "You can think of the 3 dimensional array constructed in the last exercise as an array of two **10x2** sub-matrices". It should be "two 10x**5**" sub-matrices

**Comment by TomMonks** [comment]
Thanks Pavel. Fixed in upcoming version 3.0.0. Acknowledgement added.
