### ISSUE TITLE
Documentation - Issue on page https://www.pythonhealthdatascience.com/content/001_setup/contributing.html

### ISSUE THREAD

**Issue by JeffAkkerman** [health-data-science-OR/coding-for-ml#61]
The Requests section 2nd and 4th bullet points could be improved.  It currently reads:

>Requests
>For new content requests please
>- Detail the requested content including description and lists of any relevant packages
>- Provide a case why this content relevant to health data scientist
>- Optional: provide an example
>- Label the issue an an `enhancement`

Suggested fix:

>Requests
>For new content requests please
>- Detail the requested content including description and lists of any relevant packages
>- Explain why this content is relevant to health data scientists
>- Optional: provide an example
>- Label the issue as an `enhancement`

**Comment by TomMonks** [comment]
Thanks fixed in v3.0.0
