### ISSUE TITLE
Issue on page /content/001_setup/prereq/02_dicts.html

### ISSUE THREAD

**Issue by JeffAkkerman** [health-data-science-OR/coding-for-ml#62]
Suggestion: Please label this issue as 'documentation'.

The 2nd bullet point says:

> Key and item pairs are separated by a semi colon

Suggested fix: remove "semi"

> Key and item pairs are separated by a colon

**Comment by TomMonks** [comment]
Thanks. Fixed in upcoming release v3.0.0
